### ISSUE TITLE
shift_jis的一个bug

### ISSUE THREAD

**Issue by SteveCruise** [shirne/charset-dart#2]
https://github.com/shirne/charset-dart/blob/fa46cf9fc9c6148726f8c09873525c60cc5bca96/lib/src/shift_jis.dart#L38

应该改为
```dart
return utf8.decode(result, allowMalformed: _allowMalformed);
```
因为`0xFFFD`依然会导致抛出异常FormatException: Invalid UTF-8 byte (at offset 0)，因而依然没实现兼容。
https://github.com/shirne/charset-dart/blob/fa46cf9fc9c6148726f8c09873525c60cc5bca96/lib/src/shift_jis.dart#L33

**Comment by shirne** [comment]
感谢反馈
