### ISSUE TITLE
please add cp-850 support

### ISSUE THREAD

**Issue by insinfo** [shirne/charset-dart#3]
please add cp-850 support

for decoding text in excel  MS DOS CSV sheets

**Comment by shirne** [comment]
> please add cp-850 support
> 
> for decoding text in excel MS DOS CSV sheets

https://github.com/shirne/charset-dart/blob/master/lib/src/code_page.dart#L75
is this ?
code map containts
```
    '850': cp850,
    'cp850': cp850,
    'ibm850': cp850,
    'csibm850': cp850,
```
Should i add 'cp-850' support?
