### ISSUE TITLE
Why UTF32le using list<int?> variable

### ISSUE THREAD

**Issue by farhantandia** [shirne/charset-dart#5]
Why UTF32le using list<int?> variable, for me i need to use it as Uint8list, which is could not match the Uint8list properties using List<int?> instead of normal List<int>, do you have reason for that? because the old utf package using List<int>. Or how to convert List<int?> as Uint8list?

**Comment by shirne** [comment]
You can use
```
List<int?> nullableIntList = ...;
Uint8List.fromList(nullableIntList.whereType<int>().toList());
```
to transform List<int?> to Uint8List.
